### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile while buiulding mongo-seed

### ISSUE THREAD

**Issue by Ulisses85** [SIMPATICOProject/citizenpedia#14]
Hey guys I'm receiving the following error : whil;e trying to run citizenpedia with docker-compose up command:
 
Building mongo-seed
ERROR: Cannot locate specified Dockerfile: Dockerfile

ias there any issue with mongo-seed configuration

**Comment by enriquesanz** [comment]
Hello.

A Dockerfile was missing, I don't know why. I made a quick fix to avoid that error.
