### ISSUE TITLE
"<- Volver al diagrama" button points to a wrong link

### ISSUE THREAD

**Issue by vcartelli** [SIMPATICOProject/citizenpedia#16]
HOW TO REPRODUCE:
1. go [here](https://simpatico.hi-iberia.es:4569/qae/questions/show/5beae4d44863c574cbbcae1c)
2. click on `[<- Volver al diagrama]` button.

EXPECTED RESULT:
[https://simpatico.hi-iberia.es:4570/cpd/procedures/e59287e6-ff46-46f2-948b-450bd7bc9d9e/53aac759-ff7b-467b-b4bc-516e351dd61c](https://simpatico.hi-iberia.es:4570/cpd/procedures/e59287e6-ff46-46f2-948b-450bd7bc9d9e/53aac759-ff7b-467b-b4bc-516e351dd61c)

SOLUTION:
The url must be prefixed with the cpd origin (e.g. `https://simpatico.hi-iberia.es:4570`).
Also, the diagram id should be come after /procedures (no need for the language in the path, just `origin + /cpd/procedures/{diagramId}/{elementId}`)

**Comment by enriquesanz** [comment]
Not really an issue, it is a configuration problem. The CPD path has to be changed in the config file.
