### ISSUE TITLE
i18n incomplete

### ISSUE THREAD

**Issue by kazhamiakin** [SIMPATICOProject/citizenpedia#6]
Not all the labels are translated. In particular,
- Connect with .. buttons
- Footer
- CATEGORIES (in nav menu, exists in IT and ES but not in EN)
- Hello, XXXX (signed user)
- password change page (actually, should be removed)
- days ago (in the list of questions and inside a question page)
-  Submit your answer
- Signup form

**Comment by enriquesanz** [comment]
Fixed.

**Comment by kazhamiakin** [comment]
- "by" in question details is not translated
- days ago (in the list of questions and inside a question page) is not yet translated
