### ISSUE TITLE
QAE Login fail

### ISSUE THREAD

**Issue by jrgaston-hib** [SIMPATICOProject/citizenpedia#7]
I just tested integration between qae, ife and aac and there are some problems creating questions:

    1.- I have to login everytime when I want to create a new question.
    2.- I have to login twice, because first time always fail.
    3.- When I log in correctly, the redirect is to default qae page, not to create a question with question text from IFE.

If I want to see a question from IFE, all works correctly.

**Comment by enriquesanz** [comment]
Fixed in new_design branch.
