### ISSUE TITLE
Unable to start correctly

### ISSUE THREAD

**Issue by WebDevBren** [SIMPATICOProject/citizenpedia#8]
I am unable to get this to start correctly, everything is redirected to the main index.html

You can see it here: https://components.sparta.simpatico-project.eu/ctz

We are using a pure env approach for the config. and the following are outputted.
```(bash)
#!/usr/bin/env bash 
# production Config for LOG Component

export NODE_ENV="production";
export DOMAIN="https://components.sparta.simpatico-project.eu";
export EXTERNAL_PORT=5303; # For Nginx reverse proxy
export CTZ_PATH="/ctz";

export SESSION_SECRET="ooyah7Fesh8iegoorahjuqui3tae9ingoThaed3yeiphae8roh2atai2taTheiwa"

export FACEBOOK_ID=""
export FACEBOOK_SECRET=""
export TWITTER_ID=""
export TWITTER_SECRET=""
export GOOGLE_ID=""
export GOOGLE_SECRET=""

export AAC_ID="83333c95-1e61-497a-a1ba-aafff87246bb"
export AAC_SECRET="redacted"
export AAC_ROOT_URL="https://auth.sparta.simpatico-project.eu/aac"

### DB Config

export MONGO_HOST="mongo_db"
export MONGO_ROOT_PASSWORD="redacted"
export MONGO_USERNAME="ctz_user"
export MONGO_PASSWORD="redacted"
export MONGO_DATABASE="citizenpedia"

export MONGODB_URI=$(echo mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DATABASE})


### CPD Path

export CPD_PATH="https://components.sparta.simpatico-project.eu/cpd/en/diagram"
```

i have modified the files in /server/config to include the env variables. and the fact that the mongoDB connection is successful i can say that they are working...

No errors are being reported from Express...

**Comment by enriquesanz** [comment]
Is Apache2 config correct? From the readme:

> Also, for changing the serving path, Apache2 has to be configured with a VirtualHost and a reverse proxy. E.g:

ProxyRequests Off ProxyPreserveHost On

<Location /qae> ProxyPass http://localhost:9000

Note: Be careful not to add an ending '/' to the ProxyPass path.

**Comment by WebDevBren** [comment]
We are using Nginx, not that it should be an issue see below for the vhost

```(nginx)
 ---snip---
    location /ctz {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://ctz_server;
    }
---snip---
```

**Comment by enriquesanz** [comment]
The Galicia team had the same issue using nginx and they solved it using Apache. Maybe Jesus Rubén Gastón <jrgaston@hi-iberia.es> can clarify more about this.

**Comment by enriquesanz** [comment]
I installed a new machine with only nginx and managed to made it work with the following config:

```
        location /qae {
                rewrite ^/qae/(.*) /$1 break;
                proxy_pass http://localhost:9000/;
                proxy_set_header   Host $host;
        }
```

Then, opening http://192.168.33.10/qae/ (that's my machine ip) it works fine.
